### PR TITLE
Add usage section to command help

### PR DESCRIPTION
**Pull request by smcclellan**
Now that positional arguments exist, it makes sense to render the position of
arguments in the command help.

Fixes https://tickets.puppetlabs.com/browse/RAZOR-756

### CODE REVIEW

**Comment by smcclellan** [comment]
I think this should be merged soon to follow the positional arguments work.

**Comment by steveax** [comment]
@smcclellan, I get 2 test failures:

````
Failures:

  1) Razor::CLI::Format api help displays the full help if on an older server
     Failure/Error: result.should =~ /full help is here/
       expected: /full help is here/
            got: nil (using =~)
     # ./spec/cli/format_spec.rb:167:in `(root)'

  2) Razor::CLI::Format api help displays the full help if on an older server and api is specified
     Failure/Error: result.should =~ /full help is here/
       expected: /full help is here/
            got: nil (using =~)
     # ./spec/cli/format_spec.rb:174:in `(root)'

Finished in 3.05 seconds
108 examples, 2 failures

Failed examples:

rspec ./spec/cli/format_spec.rb:163 # Razor::CLI::Format api help displays the full help if on an older server
rspec ./spec/cli/format_spec.rb:170 # Razor::CLI::Format api help displays the full help if on an older server and api is specified
````

Seems like we need an `else` for the `if item['help'].has_key?('examples')` block?

**Comment by smcclellan** [comment]
@steveax Good catch, fixed.

**Comment by steveax** [comment]
LGTM

**Pull request merged**
